// Some fields are stored for future use
#![allow(dead_code)]

pub mod bytecode;
pub mod concurrent_gc;
pub mod debug;
mod heap;
pub mod ic;
mod ops;
pub mod stackmap;
pub mod threads;
mod value;
pub mod verifier;
#[allow(clippy::module_inception)]
mod vm;

pub use debug::{DebugInfo, FunctionDebugInfo};
pub use heap::{Heap, HeapObject, ObjectType};
pub use ops::Op;
// StackMap types for precise GC (used by embedders/tools)
#[allow(unused_imports)]
pub use stackmap::{FunctionStackMap, RefBitset, StackMapEntry};
pub use value::Value;
// Verifier for bytecode validation (used by embedders/tools)
#[allow(unused_imports)]
pub use verifier::{Verifier, VerifyError};
pub use vm::VM;

/// A compiled function.
#[derive(Debug, Clone)]
pub struct Function {
    pub name: String,
    pub arity: usize,
    pub locals_count: usize,
    pub code: Vec<Op>,
    /// StackMap for GC safepoints (optional, generated by compiler)
    pub stackmap: Option<FunctionStackMap>,
}

/// A compiled chunk of bytecode.
#[derive(Debug, Clone)]
pub struct Chunk {
    pub functions: Vec<Function>,
    pub main: Function,
    /// String constants pool
    pub strings: Vec<String>,
    /// Debug information (optional)
    pub debug: Option<DebugInfo>,
}
