// Some fields are stored for future use
#![allow(dead_code)]

pub mod bytecode;
pub mod concurrent_gc;
pub mod debug;
mod heap;
pub mod microop;
pub mod microop_converter;
mod ops;
pub mod stackmap;
pub mod threads;
mod value;
pub mod verifier;
#[allow(clippy::module_inception)]
mod vm;

pub use debug::{DebugInfo, FunctionDebugInfo};
pub use heap::{GcRef, Heap};
pub use ops::Op;
// StackMap types for precise GC (used by embedders/tools)
#[allow(unused_imports)]
pub use stackmap::{FunctionStackMap, RefBitset, StackMapEntry};
pub use value::Value;
// Verifier for bytecode validation (used by embedders/tools)
#[allow(unused_imports)]
pub use verifier::{Verifier, VerifyError};
// OpcodeProfile exported for external profiling tools
#[allow(unused_imports)]
pub use vm::OpcodeProfile;
pub use vm::VM;

/// VM-level value type for the typed bytecode architecture.
///
/// All values are stored as u64 slots on the operand stack and in locals.
/// The type information is encoded in the opcodes, not in the values themselves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValueType {
    /// 32-bit integer (zero-extended in u64 slot, upper 32 bits are 0)
    I32,
    /// 64-bit integer
    I64,
    /// 32-bit float (stored as f32 bits in lower 32 bits of u64 slot)
    F32,
    /// 64-bit float (stored as f64 bits in u64 slot)
    F64,
    /// GC-managed heap reference (heap index as u64, 0 = null)
    Ref,
}

/// A compiled function.
#[derive(Debug, Clone)]
pub struct Function {
    pub name: String,
    pub arity: usize,
    pub locals_count: usize,
    pub code: Vec<Op>,
    /// StackMap for GC safepoints (optional, generated by compiler)
    pub stackmap: Option<FunctionStackMap>,
    /// Type information for local variables (indexed by slot number).
    /// Used by JIT compiler for type specialization.
    pub local_types: Vec<ValueType>,
}

/// A type descriptor for pre-allocated dyn type info objects.
#[derive(Debug, Clone, PartialEq)]
pub struct TypeDescriptor {
    /// Tag name for type matching (e.g., "int", "Point", "Vec_string")
    pub tag_name: String,
    /// Field names for struct types (empty for primitives)
    pub field_names: Vec<String>,
    /// Field type tag names for struct types (parallel to field_names).
    /// Each entry is the tag_name of the field's type descriptor.
    pub field_type_tags: Vec<String>,
    /// Auxiliary type tag names for container element types.
    /// Vec → [elem_tag], Map → [key_tag, val_tag], Array → [elem_tag], others → [].
    pub aux_type_tags: Vec<String>,
}

/// A compiled chunk of bytecode.
#[derive(Debug, Clone)]
pub struct Chunk {
    pub functions: Vec<Function>,
    pub main: Function,
    /// String constants pool
    pub strings: Vec<String>,
    /// Type descriptor table for dyn type info
    pub type_descriptors: Vec<TypeDescriptor>,
    /// Debug information (optional)
    pub debug: Option<DebugInfo>,
}
